- name: make container dir @ {{ install_dir }}
  file: path={{ install_dir }}/{{ item }} state=directory recurse=true
  with_items: folders

- name: copy over apps dockerfile
  synchronize: src="{{ app }}/" dest="{{ install_dir }}/apps/{{ main_container.name }}/" recursive=yes

- name: copy over services
  synchronize: src="{{ lookup('env', 'WHALER') }}/images/{{ item }}" dest="{{ install_dir }}/images" recursive=yes
  with_items: build
