- name: make container dir @ {{ install_dir }}
  file: path={{ install_dir }}/{{ item }} state=directory recurse=true
  with_items: folders

- name: copy over apps dockerfile
  synchronize: src="{{ app }}/" dest="{{ install_dir }}/apps/{{ main_container.name }}/" recursive=yes

- name: copy over local images
  synchronize: src="{{ lookup('env', 'WHALER') }}/images/{{ item.key }}" dest="{{ install_dir }}/images" recursive=yes
  with_dict: build
  when: build is defined
