- name: pull code down from repo
  git: repo={{ repo }}
       dest={{ install_dir }}/apps/{{ main_container.name }}/{{ dest }}
       version=master
       depth=1
       force=yes
       update=yes
       accept_hostkey=yes
