- name: build containers
  command: chdir={{ install_dir }}/images/{{ item.key }} {{ item.value }}
  with_dict: build
  when: build is defined

- name: build app
  command: chdir={{ install_dir }}/apps/{{ main_container.name }} docker build -t={{ main_container.image}} --rm=true .

- name: remove all required containers
  command: docker rm -f {{ item }}
  with_items: containers
  ignore_errors: yes

- name: run all required containers
  command: "{{ item.value.command }}"
  when: services is defined
  with_dict: services

- name: run main app container
  command: "{{ main_container.command }}"
