- name: build containers
  command: chdir={{ install_dir }}/images/{{ item }} docker build -t={{ item }} --rm=true .
  with_items: build
  register: build_results

- name: build app
  command: chdir={{ install_dir }}/apps/{{ main_container.name }} docker build -t={{ main_container.image}} --rm=true .

- name: stop all required containers
  command: docker stop {{ item }}
  with_items: containers
  ignore_errors: yes

- name: remove all required containers
  command: docker rm {{ item }}
  with_items: containers
  ignore_errors: yes

- name: run all required containers
  command: "{{ item.value.command }}"
  with_dict: services

- name: run main app container
  command: "{{ main_container.command }}"

- name: cleanup images
  shell: docker images -a|grep '^<none>'|tr -s ' '|cut -d' ' -f 3|xargs docker rmi
  # shell: docker images --no-trunc | grep none | awk '{print $3}' | xargs -r docker rmi
  ignore_errors: yes
